-- Activate required extensions
CREATE EXTENSION IF NOT EXISTS vector;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS GYM;
CREATE SCHEMA IF NOT EXISTS LLM;
CREATE SCHEMA IF NOT EXISTS LOG;

-- Temporary table for activity descriptions
DROP TABLE IF EXISTS GYM.TMP_DESCRIPTIONS;
CREATE TABLE GYM.TMP_DESCRIPTIONS (
  ACTIVITY_NAME TEXT,
  CATEGORY TEXT,
  SUB_CATEGORY TEXT,
  DESCRIPTION TEXT,
  INTENSITY_LEVEL TEXT,
  TARGET_AGE_GROUP TEXT,
  WEIGHTS_USED BOOLEAN,
  PRIMARY_BENEFIT TEXT,
  SKILL_LEVEL TEXT,
  IMPACT_LEVEL TEXT,
  SOCIAL_DYNAMIC TEXT,
  CALORIC_BURN TEXT,
  MENTAL_FOCUS TEXT,
  CONTRAINDICATIONS TEXT,
  INTERESTING_FACT TEXT
);

-- Temporary table for activities
DROP TABLE IF EXISTS GYM.TMP_ACTIVITIES;
CREATE TABLE GYM.TMP_ACTIVITIES (
  CODE CHAR(3),
  NAME TEXT,
  DURATION SMALLINT,
  NEW BOOLEAN
);

-- Temporary table for sessions (activity schedule)
DROP TABLE IF EXISTS GYM.TMP_SESSIONS;
CREATE TABLE GYM.TMP_SESSIONS (
  TIME CHAR(5),
  DAY VARCHAR(12),
  CODE CHAR(3)
);


-- Table for activity categories
DROP TABLE IF EXISTS GYM.CATEGORIES;
CREATE TABLE GYM.CATEGORIES (
  ID SMALLSERIAL PRIMARY KEY,
  CATEGORY TEXT
);

-- Table for activity subcategories
DROP TABLE IF EXISTS GYM.SUBCATEGORIES;
CREATE TABLE GYM.SUBCATEGORIES (
  ID SMALLSERIAL PRIMARY KEY,
  CATEGORY SMALLINT,
  SUBCATEGORY TEXT
);

-- Table for activity intensity levels
DROP TABLE IF EXISTS GYM.INTENSITY_LEVELS;
CREATE TABLE GYM.INTENSITY_LEVELS (
  VALUE SMALLINT,
  DESCRIPTION TEXT
);

-- Table for activity skill levels
DROP TABLE IF EXISTS GYM.SKILL_LEVELS;
CREATE TABLE GYM.SKILL_LEVELS (
  VALUE SMALLINT,
  DESCRIPTION TEXT
);

-- Table for activity impact levels
DROP TABLE IF EXISTS GYM.IMPACT_LEVELS;
CREATE TABLE GYM.IMPACT_LEVELS(
  VALUE SMALLINT,
  DESCRIPTION TEXT
);

-- Table for activity caloric burns
DROP TABLE IF EXISTS GYM.CALORIC_BURNS;
CREATE TABLE GYM.CALORIC_BURNS (
  VALUE SMALLINT,
  DESCRIPTION TEXT
);

-- Table for activities
DROP TABLE IF EXISTS GYM.ACTIVITIES;
CREATE TABLE GYM.ACTIVITIES (
  ACTIVITY_CODE TEXT,
  ACTIVITY_NAME TEXT,
  CATEGORY SMALLINT,
  SUBCATEGORY SMALLINT,
  INTENSITY_LEVEL SMALLINT,
  SKILL_LEVEL SMALLINT,
  IMPACT_LEVEL SMALLINT,
  CALORIC_BURN SMALLINT,
  WEIGHTS_USED BOOLEAN,
  DESCRIPTION TEXT,
  PRIMARY_BENEFIT TEXT,
  CONTRAINDICATIONS TEXT,
  INTERESTING_FACT TEXT,
  IS_NEW BOOLEAN
);

-- Table for embeddings
DROP TABLE IF EXISTS GYM.EMBEDDINGS;
CREATE TABLE GYM.EMBEDDINGS (
    ACTIVITY_CODE CHAR(3),
    ACTIVITY_NAME TEXT,
    CONTENT TEXT,
    EMBEDDING VECTOR(1536)
);

-- Table for embeddings
DROP TABLE IF EXISTS GYM.SESSIONS;
CREATE TABLE GYM.SESSIONS (
    ACTIVITY_CODE CHAR(3),
    DAY SMALLINT,
    DOW CHAR(10),
    CTIME CHAR(5),
    DURATION SMALLINT,
    TIME TIME
);


DROP VIEW GYM.VW_SESSIONS;
CREATE VIEW GYM.VW_SESSIONS AS 
SELECT 
  A.ACTIVITY_NAME,
  S.DOW,
  S.CTIME AS TIME,
  S.DURATION,
  A.WEIGHTS_USED

FROM GYM.ACTIVITIES A
LEFT JOIN GYM.SESSIONS S 
  ON A.ACTIVITY_CODE = S.ACTIVITY_CODE;