-- Activate required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS vector;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS GYM2;
CREATE SCHEMA IF NOT EXISTS LLM2;
CREATE SCHEMA IF NOT EXISTS LOG2;

-- Temporary table for activity descriptions
DROP TABLE IF EXISTS GYM2.TMP_DESCRIPTIONS;
CREATE TABLE GYM2.TMP_DESCRIPTIONS (
  ACTIVITY_NAME TEXT,
  CATEGORY TEXT,
  SUB_CATEGORY TEXT,
  DESCRIPTION TEXT,
  INTENSITY_LEVEL TEXT,
  TARGET_AGE_GROUP TEXT,
  WEIGHTS_USED BOOLEAN,
  PRIMARY_BENEFIT TEXT,
  SKILL_LEVEL TEXT,
  IMPACT_LEVEL TEXT,
  SOCIAL_DYNAMIC TEXT,
  CALORIC_BURN TEXT,
  MENTAL_FOCUS TEXT,
  CONTRAINDICATIONS TEXT,
  INTERESTING_FACT TEXT
);

-- Temporary table for activities
DROP TABLE IF EXISTS GYM2.TMP_ACTIVITIES;
CREATE TABLE GYM2.TMP_ACTIVITIES (
  CODE CHAR(3),
  NAME TEXT,
  DURATION SMALLINT,
  NEW BOOLEAN
);

-- Temporary table for sessions (activity schedule)
DROP TABLE IF EXISTS GYM2.TMP_SESSIONS;
CREATE TABLE GYM2.TMP_SESSIONS (
  TIME CHAR(5),
  DAY VARCHAR(12),
  CODE CHAR(3)
);


-- Table for activity categories
DROP TABLE IF EXISTS GYM2.CATEGORIES;
CREATE TABLE GYM2.CATEGORIES (
  ID SMALLSERIAL PRIMARY KEY,
  CATEGORY TEXT
);

-- Table for activity subcategories
DROP TABLE IF EXISTS GYM2.SUBCATEGORIES;
CREATE TABLE GYM2.SUBCATEGORIES (
  ID SMALLSERIAL PRIMARY KEY,
  CATEGORY SMALLINT,
  SUBCATEGORY TEXT
);

-- Table for activity intensity levels
DROP TABLE IF EXISTS GYM2.INTENSITY_LEVELS;
CREATE TABLE GYM2.INTENSITY_LEVELS (
  VALUE SMALLINT,
  DESCRIPTION TEXT
);

-- Table for activity skill levels
DROP TABLE IF EXISTS GYM2.SKILL_LEVELS;
CREATE TABLE GYM2.SKILL_LEVELS (
  VALUE SMALLINT,
  DESCRIPTION TEXT
);

-- Table for activity impact levels
DROP TABLE IF EXISTS GYM2.IMPACT_LEVELS;
CREATE TABLE GYM2.IMPACT_LEVELS(
  VALUE SMALLINT,
  DESCRIPTION TEXT
);

-- Table for activity caloric burns
DROP TABLE IF EXISTS GYM2.CALORIC_BURNS;
CREATE TABLE GYM2.CALORIC_BURNS (
  VALUE SMALLINT,
  DESCRIPTION TEXT
);

-- Table for activities
DROP TABLE IF EXISTS GYM2.ACTIVITIES;
CREATE TABLE GYM2.ACTIVITIES (
  ACTIVITY_CODE TEXT,
  ACTIVITY_NAME TEXT,
  CATEGORY SMALLINT,
  SUBCATEGORY SMALLINT,
  INTENSITY_LEVEL SMALLINT,
  SKILL_LEVEL SMALLINT,
  IMPACT_LEVEL SMALLINT,
  CALORIC_BURN SMALLINT,
  WEIGHTS_USED BOOLEAN,
  DESCRIPTION TEXT,
  PRIMARY_BENEFIT TEXT,
  CONTRAINDICATIONS TEXT,
  INTERESTING_FACT TEXT,
  IS_NEW BOOLEAN
);

-- Table for embeddings
DROP TABLE IF EXISTS GYM2.EMBEDDINGS;
CREATE TABLE GYM2.EMBEDDINGS (
    ACTIVITY_CODE CHAR(3),
    ACTIVITY_NAME TEXT,
    CONTENT TEXT,
    EMBEDDING VECTOR(1536)
);

-- Table for embeddings
DROP TABLE IF EXISTS GYM2.SESSIONS;
CREATE TABLE GYM2.SESSIONS (
    ACTIVITY_CODE CHAR(3),
    DAY SMALLINT,
    DOW CHAR(10),
    CTIME CHAR(5),
    DURATION SMALLINT,
    TIME TIME
);
