TRUNCATE TABLE GYM2.ACTIVITIES;
INSERT INTO GYM2.ACTIVITIES(ACTIVITY_CODE,ACTIVITY_NAME,CATEGORY,SUBCATEGORY,
  WEIGHTS_USED,INTENSITY_LEVEL, SKILL_LEVEL,IMPACT_LEVEL,CALORIC_BURN,
  DESCRIPTION,PRIMARY_BENEFIT,CONTRAINDICATIONS,INTERESTING_FACT,IS_NEW)
SELECT 
  A.CODE,
  D.ACTIVITY_NAME,
  C.ID,
  S.ID,
  D.WEIGHTS_USED,
  CASE 
    WHEN IMPACT_LEVEL = 'No-impact' THEN 0
    WHEN IMPACT_LEVEL = 'No-impact to Low-impact' THEN 1
    WHEN IMPACT_LEVEL = 'Low-impact' THEN 2
    WHEN IMPACT_LEVEL = 'Low to Medium-impact' THEN 3
    WHEN IMPACT_LEVEL = 'Medium-impact' THEN 4
    WHEN IMPACT_LEVEL = 'Medium to High-impact' THEN 5
    WHEN IMPACT_LEVEL = 'High-impact' THEN 6
    WHEN IMPACT_LEVEL LIKE 'Low-impact%' THEN 2
    WHEN IMPACT_LEVEL LIKE 'Medium-impact%' THEN 4
    WHEN IMPACT_LEVEL LIKE 'Medium to High-impact%' THEN 5
    WHEN IMPACT_LEVEL LIKE 'High-impact%' THEN 6
    ELSE -1
  END,
  CASE 
    WHEN SKILL_LEVEL = 'Low' THEN 2
    WHEN SKILL_LEVEL = 'Low to Medium' THEN 3
    WHEN SKILL_LEVEL = 'Medium' THEN 4
    WHEN SKILL_LEVEL = 'Medium to High' THEN 5
    WHEN SKILL_LEVEL = 'High' THEN 6
    WHEN SKILL_LEVEL LIKE 'Medium%' THEN 4
    WHEN SKILL_LEVEL LIKE 'High%' THEN 6
    ELSE -1
  END,
  CASE 
    WHEN IMPACT_LEVEL = 'No-impact' THEN 0
    WHEN IMPACT_LEVEL = 'No-impact to Low-impact' THEN 1
    WHEN IMPACT_LEVEL = 'Low-impact' THEN 2
    WHEN IMPACT_LEVEL = 'Low to Medium-impact' THEN 3
    WHEN IMPACT_LEVEL = 'Medium-impact' THEN 4
    WHEN IMPACT_LEVEL = 'Medium to High-impact' THEN 5
    WHEN IMPACT_LEVEL = 'High-impact' THEN 6
    WHEN IMPACT_LEVEL LIKE 'Low-impact%' THEN 2
    WHEN IMPACT_LEVEL LIKE 'Medium-impact%' THEN 4
    WHEN IMPACT_LEVEL LIKE 'Medium to High-impact%' THEN 5
    WHEN IMPACT_LEVEL LIKE 'High-impact%' THEN 6
    ELSE -1
  END,
  CASE 
    WHEN CALORIC_BURN = 'Low' THEN 2
    WHEN CALORIC_BURN = 'Low to Medium' THEN 3
    WHEN CALORIC_BURN = 'Medium' THEN 4
    WHEN CALORIC_BURN = 'Medium to High' THEN 5
    WHEN CALORIC_BURN = 'High' THEN 6
    WHEN CALORIC_BURN = 'Very High' THEN 8
    WHEN CALORIC_BURN LIKE 'Low%' THEN 2
    WHEN CALORIC_BURN LIKE 'Medium%' THEN 4
    WHEN CALORIC_BURN LIKE 'High%' THEN 6
    WHEN CALORIC_BURN LIKE 'Very High%' THEN 8
    ELSE -1
  END,
  D.DESCRIPTION,
  D.PRIMARY_BENEFIT,
  D.CONTRAINDICATIONS,
  D.INTERESTING_FACT,
  A.NEW
FROM GYM2.TMP_DESCRIPTIONS D
LEFT JOIN GYM2.TMP_ACTIVITIES A
  ON D.ACTIVITY_NAME = A.NAME
LEFT JOIN GYM2.CATEGORIES C
  ON D.CATEGORY=C.CATEGORY
LEFT JOIN GYM2.SUBCATEGORIES S
  ON C.ID = S.CATEGORY
    AND D.SUB_CATEGORY=S.SUBCATEGORY;

TRUNCATE TABLE GYM2.EMBEDDINGS;
INSERT INTO GYM2.EMBEDDINGS(ACTIVITY_CODE,ACTIVITY_NAME,
  CONTENT) 
SELECT 
  A.CODE,
  D.ACTIVITY_NAME,
  CONCAT_WS(
    E'\n',
    CONCAT('#Name: ',D.ACTIVITY_NAME),
    CONCAT('##Category: ',C.CATEGORY),
    CONCAT('##Subcategory: ',S.SUBCATEGORY),
    CONCAT('##Description: ',D.DESCRIPTION),
    CONCAT('##Primary benefit: ',D.PRIMARY_BENEFIT),
    CONCAT('##Contraindications: ',D.CONTRAINDICATIONS),
    CONCAT('##Interesting fact: ',D.INTERESTING_FACT),
    CONCAT('##Social dynamic: ',D.SOCIAL_DYNAMIC)
  )
FROM GYM2.TMP_DESCRIPTIONS D
LEFT JOIN GYM2.TMP_ACTIVITIES A
  ON D.ACTIVITY_NAME = A.NAME
LEFT JOIN GYM2.CATEGORIES C
  ON D.CATEGORY = C.CATEGORY
LEFT JOIN GYM2.SUBCATEGORIES S
  ON C.ID = S.CATEGORY
    AND D.SUB_CATEGORY=S.SUBCATEGORY;


TRUNCATE TABLE GYM2.SESSIONS;
INSERT INTO GYM2.SESSIONS(ACTIVITY_CODE, DAY, DOW, CTIME, DURATION, TIME) 
SELECT 
  S.CODE,
  CASE S.DAY
    WHEN 'sunday'    THEN 0
    WHEN 'monday'    THEN 1
    WHEN 'tuesday'   THEN 2
    WHEN 'wednesday' THEN 3
    WHEN 'thursday'  THEN 4
    WHEN 'friday'    THEN 5
    WHEN 'saturday'  THEN 6
  END,
  S.DAY,
  S.TIME,
  A.DURATION,
  S.TIME::TIME
FROM GYM2.TMP_SESSIONS S
LEFT JOIN GYM2.TMP_ACTIVITIES A
  ON S.CODE = A.CODE;
