TRUNCATE TABLE GYM.CATEGORIES RESTART IDENTITY;
INSERT INTO GYM.CATEGORIES(CATEGORY)
SELECT DISTINCT CATEGORY
FROM GYM.TMP_DESCRIPTIONS;

TRUNCATE TABLE GYM.SUBCATEGORIES RESTART IDENTITY;
INSERT INTO GYM.SUBCATEGORIES(CATEGORY,SUBCATEGORY)
SELECT DISTINCT C.ID, A.SUB_CATEGORY
FROM GYM.TMP_DESCRIPTIONS A
LEFT JOIN GYM.CATEGORIES C
ON A.CATEGORY = C.CATEGORY;

TRUNCATE TABLE GYM.INTENSITY_LEVELS;
INSERT INTO GYM.INTENSITY_LEVELS (VALUE,DESCRIPTION)
VALUES (2,'Low'),(3, 'Low to Medium'),(4, 'Medium'),(5,'Medium to High'),(6,'High'),
  (7,'High to Extreme'),(8,'Very high');

TRUNCATE TABLE GYM.SKILL_LEVELS;
INSERT INTO GYM.SKILL_LEVELS (VALUE,DESCRIPTION)
VALUES (2,'Low'),(3, 'Low to Medium'),(4, 'Medium'),(5,'Medium to High'),(6,'High');

TRUNCATE TABLE GYM.IMPACT_LEVELS;
INSERT INTO GYM.IMPACT_LEVELS (VALUE,DESCRIPTION)
VALUES (0, 'No-impact'),(1,'No-impact to Low-impact'),
(2,'Low'),(3, 'Low to Medium'),(4, 'Medium'),(5,'Medium to High'),(6,'High');

TRUNCATE TABLE GYM.CALORIC_BURNS;
INSERT INTO GYM.CALORIC_BURNS (VALUE,DESCRIPTION)
VALUES (2,'Low'),(3, 'Low to Medium'),(4, 'Medium'),(5,'Medium to High'),(6,'High'),(8,'Very high');