TRUNCATE TABLE GYM2.CATEGORIES RESTART IDENTITY;
INSERT INTO GYM2.CATEGORIES(CATEGORY)
SELECT DISTINCT CATEGORY
FROM GYM2.TMP_DESCRIPTIONS;

TRUNCATE TABLE GYM2.SUBCATEGORIES RESTART IDENTITY;
INSERT INTO GYM2.SUBCATEGORIES(CATEGORY,SUBCATEGORY)
SELECT DISTINCT C.ID, A.SUB_CATEGORY
FROM GYM2.TMP_DESCRIPTIONS A
LEFT JOIN GYM2.CATEGORIES C
ON A.CATEGORY = C.CATEGORY;

TRUNCATE TABLE GYM2.INTENSITY_LEVELS;
INSERT INTO GYM2.INTENSITY_LEVELS (VALUE,DESCRIPTION)
VALUES (2,'Low'),(3, 'Low to Medium'),(4, 'Medium'),(5,'Medium to High'),(6,'High'),
  (7,'High to Extreme'),(8,'Very high');

TRUNCATE TABLE GYM2.SKILL_LEVELS;
INSERT INTO GYM2.SKILL_LEVELS (VALUE,DESCRIPTION)
VALUES (2,'Low'),(3, 'Low to Medium'),(4, 'Medium'),(5,'Medium to High'),(6,'High');

TRUNCATE TABLE GYM2.IMPACT_LEVELS;
INSERT INTO GYM2.IMPACT_LEVELS (VALUE,DESCRIPTION)
VALUES (0, 'No-impact'),(1,'No-impact to Low-impact'),
(2,'Low'),(3, 'Low to Medium'),(4, 'Medium'),(5,'Medium to High'),(6,'High');

TRUNCATE TABLE GYM2.CALORIC_BURNS;
INSERT INTO GYM2.CALORIC_BURNS (VALUE,DESCRIPTION)
VALUES (2,'Low'),(3, 'Low to Medium'),(4, 'Medium'),(5,'Medium to High'),(6,'High'),(8,'Very high');