INSERT INTO GYM.QUESTIONS(ACTIVITY_NAME,QUESTION) VALUES
('Antigravity Yoga','Which activity involves performing advanced stretching and inversions without compressing the spine or putting pressure on the joints?'),
('Antigravity Yoga','Which activity is contraindicated for individuals with high blood pressure due to frequent inverted positions?'),
('Antigravity Yoga','Is there any yoga activity which is contraindicated for high blood pressure participants?'),
('Antigravity Yoga','Does any yoga activity involve performing advanced stretching and inversions without compressing the spine or putting pressure on the joints?'),
('Antigravity Yoga','Does any activity involve performing advanced stretching and inversions without compressing the spine or putting pressure on the joints?'),
('Antigravity Yoga','Is there any activity that is contraindicated for pregnant participants due to frequent inverted positions?'),
('Bootcamp','Which fitness class features rapid transitions between aerobic and strength intervals?'),
('Bootcamp','Which group fitness class incorporates team building or partner activities?'),
('Bootcamp','Which class involves using functional equipment training like sandbags and battle ropes?'),
('Bootcamp','Which fitness class is military-style?'),
('Bootcamp','Which class is known for its high group/team environment?'),
('Bootcamp','Which fitness class includes burpees, push-ups, and planks in its programming?'),
('Bootcamp','Which class is designed to create a high-bonding environment?'),
('Bootcamp','Which fitness class is fast and challenging?'),
('Bootcamp','Which class is often associated with fat loss and full-body conditioning?'),
('Bootcamp','Which group fitness class is not recommended for those with severe spinal issues or wrist pain?'),
('Cycling HIIT','Does any activity involve max-effort sprints followed by brief rest intervals on a stationary bike?'),
('Cycling HIIT','Is there any activity that can cause your metabolism to remain highly elevated and burn extra fat for up to 24 hours after finishing a session?'),
('Cycling HIIT','Does any activity involve max-effort sprints followed by brief rest intervals on a stationary bike?'),
('Cycling HIIT','Is there any activity that can cause your metabolism to remain highly elevated and burn extra fat for up to 24 hours after finishing a session?'),
('Elle Fitness','Which activity emphasizes lean muscle stamina, metabolic speed, and a highly supportive group atmosphere?'),
('Elle Fitness','Is there any activity structuring its pacing to deliver an athletic, full-body sweat without overloading vulnerable connective joints?'),
('Elle Strong','Which activity ditches high-impact cardio jumping, focusing instead on progressive compound lifting, muscle hypertrophy, and structural form?'),
('Elle Strong','Which activity requires proper form tracking for individuals with pre-existing spinal herniations?'),
('Hybrid','What type of training involves alternating between structural barbell or dumbbell lifting blocks and intense cardiovascular conditioning blocks?'),
('Hybrid','What fitness class combines strength training and cardiovascular endurance within a single session, designed to build an athletic, well-rounded physique?'),
('Hybrid','Which activity combines strength training and cardiovascular endurance within a single session?'),
('Hybrid','Which activity is the fastest-growing sector in modern fitness, mirroring the functional demands of everyday life?'),
('Hybrid','Does any activity involve alternating between structural barbell or dumbbell lifting blocks and intense cardiovascular conditioning blocks?'),
('Hybrid Max','Is there any activity that is designed for seasoned athletes or high-level fitness enthusiasts looking to push their aerobic and anaerobic thresholds to their absolute limits?'),
('Hybrid Max','Does any activity involve heavier lifting targets, longer cardio blocks, and shorter recovery intervals?'),
('Hyrox','Which activity combines explosive leg power with grip strength and core bracing under fatigue?'),
('Hyrox','Any activity involves moving up to 175kg?'),
('Inspired Ashtanga','Which activity features a specific, continuous sequence of postures synchronized with deep belly breathing (Ujjayi pranayama)?'),
('Inspired Ashtanga','Is there an activity which requires complete mental control over every muscle group?'),
('Pilates','Which activity emphasizes core control and length rather than muscle bulk?'),
('Pilates','Which activity involves deep belly breathing (Ujjayi pranayama) other than Inspired Ashtanga?'),
('RCVRI','Which activity combines active mobility work, foam rolling, and guided breathing techniques to help the nervous system reset and muscles recover from intense training?'),
('RCVRI','Is there any activity that helps switch the nervous system from the "fight or flight" sympathetic state into the "rest and digest" parasympathetic state, accelerating muscle repair?'),
('Rig','Which activity involves using suspension trainers on a structural rig to engage the core constantly?'),
('Rig','Is there any activity that blends strength and coordination in an engaging, athletic format, incorporating hanging movements and landmine presses?'),
('Strongman','Which activity involves lifting, carrying, and pushing heavy, unusual objects like stones, sandbags, logs, and axle barbells to build powerful core strength and explosive power?'),
('Strongman','Is there any activity that strictly advises against participation for individuals with chronic lower back pain, disc issues, or severe joint degeneration?'),
('Yin Yan Yoga','Is there any activity that combines active and passive styles, featuring an active, heat-building Vinyasa flow in the first half and passive, deep floor stretches in the second half?'),
('Yin Yan Yoga','Does any activity mirror the concept of duality, helping participants build physical strength while cultivating deep mental calmness?'),
('Zumba','Which activity is a high-energy, cardio dance class that features Latin and international music rhythms, mixing low-intensity and high-intensity moves into an interval-style dance party?'),
('Zumba','Is there any activity that was created in Colombia during the 1990s when an instructor forgot his regular aerobics music and used his personal Latin music tapes instead?');