CREATE SCHEMA IF NOT EXISTS GYM;


DROP TABLE IF EXISTS GYM.RAW_ACTIVITIES;
CREATE TABLE GYM.RAW_ACTIVITIES (
  ACTIVITY_NAME TEXT,
  CATEGORY TEXT,
  SUBCATEGORY TEXT,
  DESCRIPTION TEXT,
  INTENSITY_LEVEL TEXT,
  TARGET_AGE_GROUP TEXT,
  WEIGHTS_USED BOOLEAN,
  PRIMARY_BENEFIT TEXT,
  SKILL_LEVEL TEXT,
  IMPACT_LEVEL TEXT,
  SOCIAL_DYNAMIC TEXT,
  CALORIC_BURN TEXT,
  MENTAL_FOCUS TEXT,
  CONTRAINDICATIONS TEXT,
  INTERESTING_FACT TEXT
);

DROP TABLE IF EXISTS GYM.CATEGORIES;
CREATE TABLE GYM.CATEGORIES (
  ID SMALLSERIAL PRIMARY KEY,
  CATEGORY TEXT
);

DROP TABLE IF EXISTS GYM.SUBCATEGORIES;
CREATE TABLE GYM.SUBCATEGORIES (
  ID SMALLSERIAL PRIMARY KEY,
  CATEGORY SMALLINT,
  SUBCATEGORY TEXT
);

DROP TABLE IF EXISTS GYM.INTENSITY_LEVELS;
CREATE TABLE GYM.INTENSITY_LEVELS (
  VALUE SMALLINT,
  DESCRIPTION TEXT
);

DROP TABLE IF EXISTS GYM.SKILL_LEVELS;
CREATE TABLE GYM.SKILL_LEVELS (
  VALUE SMALLINT,
  DESCRIPTION TEXT
);

DROP TABLE IF EXISTS GYM.IMPACT_LEVELS;
CREATE TABLE GYM.IMPACT_LEVELS(
  VALUE SMALLINT,
  DESCRIPTION TEXT
);

-- DROP TABLE IF EXISTS GYM.SOCIAL_DYNAMICS;
-- CREATE TABLE GYM.SOCIAL_DYNAMICS (
--   VALUE SMALLINT,
--   DESCRIPTION TEXT
-- );

DROP TABLE IF EXISTS GYM.CALORIC_BURNS;
CREATE TABLE GYM.CALORIC_BURNS (
  VALUE SMALLINT,
  DESCRIPTION TEXT
);

DROP TABLE IF EXISTS GYM.ACTIVITIES;
CREATE TABLE GYM.ACTIVITIES (
  ID SMALLSERIAL PRIMARY KEY,
  ACTIVITY_NAME TEXT,
  CATEGORY SMALLINT,
  SUBCATEGORY SMALLINT,
--  DESCRIPTION TEXT,
  INTENSITY_LEVEL SMALLINT,
--  TARGET_AGE_GROUP TEXT,
  WEIGHTS_USED BOOLEAN,
--  PRIMARY_BENEFIT TEXT,
  SKILL_LEVEL SMALLINT,
  IMPACT_LEVEL SMALLINT,
--  SOCIAL_DYNAMIC TEXT,
  CALORIC_BURN SMALLINT,
--  MENTAL_FOCUS TEXT,
--  CONTRAINDICATIONS TEXT,
--  INTERESTING_FACT TEXT
  FULL_DESCRIPTION TEXT
);

CREATE OR REPLACE VIEW GYM.VW_ACTIVITIES AS
SELECT 
    A.ID,
    A.ACTIVITY_NAME,
    C.CATEGORY,
    SC.SUBCATEGORY,
    A.WEIGHTS_USED,
    IL.DESCRIPTION AS INTENSITY_LEVEL,
    SL.DESCRIPTION AS SKILL_LEVEL,
    IML.DESCRIPTION AS IMPACT_LEVEL,
    CB.DESCRIPTION AS CALORIC_BURN,
    A.FULL_DESCRIPTION,
    EMBEDDING VECTOR(1536)
FROM GYM.ACTIVITIES A
LEFT JOIN GYM.CATEGORIES C 
    ON A.CATEGORY = C.ID
LEFT JOIN GYM.SUBCATEGORIES SC 
    ON A.SUBCATEGORY = SC.ID
LEFT JOIN GYM.INTENSITY_LEVEL IL 
    ON A.INTENSITY_LEVEL = IL.VALUE
LEFT JOIN GYM.SKILL_LEVEL SL 
    ON A.SKILL_LEVEL = SL.VALUE
LEFT JOIN GYM.IMPACT_LEVEL IML 
    ON A.IMPACT_LEVEL = IML.VALUE
LEFT JOIN GYM.CALORIC_BURN CB 
    ON A.CALORIC_BURN = CB.VALUE;

TRUNCATE TABLE GYM.CATEGORIES RESTART IDENTITY;
INSERT INTO GYM.CATEGORIES(CATEGORY) SELECT DISTINCT CATEGORY FROM GYM.RAW_ACTIVITIES;
TRUNCATE TABLE GYM.SUBCATEGORIES RESTART IDENTITY;
INSERT INTO GYM.SUBCATEGORIES(CATEGORY,SUBCATEGORY) 
  SELECT DISTINCT C.ID, A.SUBCATEGORY
  FROM GYM.RAW_ACTIVITIES A
  LEFT JOIN GYM.CATEGORIES C
  ON A.CATEGORY = C.CATEGORY;


TRUNCATE TABLE GYM.INTENSITY_LEVELS;
INSERT INTO GYM.INTENSITY_LEVELS (VALUE,DESCRIPTION)
SELECT DISTINCT
  CASE 
    WHEN INTENSITY_LEVEL = 'Low' THEN 2
    WHEN INTENSITY_LEVEL = 'Low to Medium' THEN 3
    WHEN INTENSITY_LEVEL = 'Medium' THEN 4
    WHEN INTENSITY_LEVEL = 'Medium to High' THEN 5
    WHEN INTENSITY_LEVEL = 'High' THEN 6
    WHEN INTENSITY_LEVEL = 'High to Extreme' THEN 7
    WHEN INTENSITY_LEVEL = 'Extreme' THEN 8
    WHEN INTENSITY_LEVEL LIKE 'Medium%' THEN 4
    WHEN INTENSITY_LEVEL LIKE 'High%' THEN 6
    ELSE -1
  END,
  CASE 
    WHEN INTENSITY_LEVEL = 'Low' THEN 'Low'
    WHEN INTENSITY_LEVEL = 'Low to Medium' THEN 'Low to Medium'
    WHEN INTENSITY_LEVEL = 'Medium' THEN 'Medium'
    WHEN INTENSITY_LEVEL = 'Medium to High' THEN 'Medium to High'
    WHEN INTENSITY_LEVEL = 'High' THEN 'High'
    WHEN INTENSITY_LEVEL = 'High to Extreme' THEN 'High to Extreme'
    WHEN INTENSITY_LEVEL = 'Extreme' THEN 'Extreme'
    WHEN INTENSITY_LEVEL LIKE 'Medium%' THEN 'Medium'
    WHEN INTENSITY_LEVEL LIKE 'High%' THEN 'High'
    ELSE ''
  END
FROM GYM.RAW_ACTIVITIES;

TRUNCATE TABLE GYM.SKILL_LEVELS;
INSERT INTO GYM.SKILL_LEVELS (VALUE,DESCRIPTION)
SELECT DISTINCT
  CASE 
    WHEN SKILL_LEVEL = 'Low' THEN 2
    WHEN SKILL_LEVEL = 'Low to Medium' THEN 3
    WHEN SKILL_LEVEL = 'Medium' THEN 4
    WHEN SKILL_LEVEL = 'Medium to High' THEN 5
    WHEN SKILL_LEVEL = 'High' THEN 6
    WHEN SKILL_LEVEL LIKE 'Medium%' THEN 4
    WHEN SKILL_LEVEL LIKE 'High%' THEN 6
    ELSE -1
  END,
  CASE 
    WHEN SKILL_LEVEL = 'Low' THEN 'Low'
    WHEN SKILL_LEVEL = 'Low to Medium' THEN 'Low to Medium'
    WHEN SKILL_LEVEL = 'Medium' THEN 'Medium'
    WHEN SKILL_LEVEL = 'Medium to High' THEN 'Medium to High'
    WHEN SKILL_LEVEL = 'High' THEN 'High'
    WHEN SKILL_LEVEL LIKE 'Medium%' THEN 'Medium'
    WHEN SKILL_LEVEL LIKE 'High%' THEN 'High'
    ELSE ''
  END
FROM GYM.RAW_ACTIVITIES;

TRUNCATE TABLE GYM.IMPACT_LEVELS;
INSERT INTO GYM.IMPACT_LEVELS (VALUE,DESCRIPTION)
SELECT DISTINCT
  CASE 
    WHEN IMPACT_LEVEL = 'No-impact' THEN 0
    WHEN IMPACT_LEVEL = 'No-impact to Low-impact' THEN 1
    WHEN IMPACT_LEVEL = 'Low-impact' THEN 2
    WHEN IMPACT_LEVEL = 'Low to Medium-impact' THEN 3
    WHEN IMPACT_LEVEL = 'Medium-impact' THEN 4
    WHEN IMPACT_LEVEL = 'Medium to High-impact' THEN 5
    WHEN IMPACT_LEVEL = 'High-impact' THEN 6
    WHEN IMPACT_LEVEL LIKE 'Low-impact%' THEN 2
    WHEN IMPACT_LEVEL LIKE 'Medium-impact%' THEN 4
    WHEN IMPACT_LEVEL LIKE 'Medium to High-impact%' THEN 5
    WHEN IMPACT_LEVEL LIKE 'High-impact%' THEN 6
    ELSE -1
  END,
  CASE 
    WHEN IMPACT_LEVEL = 'No-impact' THEN 'None'
    WHEN IMPACT_LEVEL = 'No-impact to Low-impact' THEN 'None to Low'
    WHEN IMPACT_LEVEL = 'Low-impact' THEN 'Low'
    WHEN IMPACT_LEVEL = 'Low to Medium-impact' THEN 'Low to Medium'
    WHEN IMPACT_LEVEL = 'Medium-impact' THEN 'Medium'
    WHEN IMPACT_LEVEL = 'Medium to High-impact' THEN 'Medium to High'
    WHEN IMPACT_LEVEL = 'High-impact' THEN 'High'
    WHEN IMPACT_LEVEL LIKE 'Low-impact%' THEN 'Low'
    WHEN IMPACT_LEVEL LIKE 'Medium-impact%' THEN 'Medium'
    WHEN IMPACT_LEVEL LIKE 'Medium to High-impact%' THEN 'Medium to High'
    WHEN IMPACT_LEVEL LIKE 'High-impact%' THEN 'High'
    ELSE ''
  END
FROM GYM.RAW_ACTIVITIES;

TRUNCATE TABLE GYM.CALORIC_BURNS;
INSERT INTO GYM.CALORIC_BURNS (VALUE,DESCRIPTION)
SELECT DISTINCT
  CASE 
    WHEN CALORIC_BURN = 'Low' THEN 2
    WHEN CALORIC_BURN = 'Low to Medium' THEN 3
    WHEN CALORIC_BURN = 'Medium' THEN 4
    WHEN CALORIC_BURN = 'Medium to High' THEN 5
    WHEN CALORIC_BURN = 'High' THEN 6
    WHEN CALORIC_BURN = 'Very High' THEN 8
    WHEN CALORIC_BURN LIKE 'Low%' THEN 2
    WHEN CALORIC_BURN LIKE 'Medium%' THEN 4
    WHEN CALORIC_BURN LIKE 'High%' THEN 6
    WHEN CALORIC_BURN LIKE 'Very High%' THEN 8
    ELSE -1
  END,
  CASE 
    WHEN CALORIC_BURN = 'Low' THEN 'Low'
    WHEN CALORIC_BURN = 'Low to Medium' THEN 'Low to Medium'
    WHEN CALORIC_BURN = 'Medium' THEN 'Medium'
    WHEN CALORIC_BURN = 'Medium to High' THEN 'Medium to High'
    WHEN CALORIC_BURN = 'High' THEN 'High'
    WHEN CALORIC_BURN = 'Very High' THEN 'Very High'
    WHEN CALORIC_BURN LIKE 'Low%' THEN 'Low'
    WHEN CALORIC_BURN LIKE 'Medium%' THEN 'Medium'
    WHEN CALORIC_BURN LIKE 'High%' THEN 'High'
    WHEN CALORIC_BURN LIKE 'Very High%' THEN 'Very High'
    ELSE ''
  END
FROM GYM.RAW_ACTIVITIES;

TRUNCATE TABLE GYM.ACTIVITIES;
INSERT INTO GYM.ACTIVITIES(ACTIVITY_NAME,CATEGORY,SUBCATEGORY,WEIGHTS_USED,INTENSITY_LEVEL,
  SKILL_LEVEL,IMPACT_LEVEL,CALORIC_BURN,FULL_DESCRIPTION) 
SELECT 
  ACTIVITY_NAME,
  C.ID,
  S.ID,
  WEIGHTS_USED,
  CASE 
    WHEN IMPACT_LEVEL = 'No-impact' THEN 0
    WHEN IMPACT_LEVEL = 'No-impact to Low-impact' THEN 1
    WHEN IMPACT_LEVEL = 'Low-impact' THEN 2
    WHEN IMPACT_LEVEL = 'Low to Medium-impact' THEN 3
    WHEN IMPACT_LEVEL = 'Medium-impact' THEN 4
    WHEN IMPACT_LEVEL = 'Medium to High-impact' THEN 5
    WHEN IMPACT_LEVEL = 'High-impact' THEN 6
    WHEN IMPACT_LEVEL LIKE 'Low-impact%' THEN 2
    WHEN IMPACT_LEVEL LIKE 'Medium-impact%' THEN 4
    WHEN IMPACT_LEVEL LIKE 'Medium to High-impact%' THEN 5
    WHEN IMPACT_LEVEL LIKE 'High-impact%' THEN 6
    ELSE -1
  END,
  CASE 
    WHEN SKILL_LEVEL = 'Low' THEN 2
    WHEN SKILL_LEVEL = 'Low to Medium' THEN 3
    WHEN SKILL_LEVEL = 'Medium' THEN 4
    WHEN SKILL_LEVEL = 'Medium to High' THEN 5
    WHEN SKILL_LEVEL = 'High' THEN 6
    WHEN SKILL_LEVEL LIKE 'Medium%' THEN 4
    WHEN SKILL_LEVEL LIKE 'High%' THEN 6
    ELSE -1
  END,
  CASE 
    WHEN IMPACT_LEVEL = 'No-impact' THEN 0
    WHEN IMPACT_LEVEL = 'No-impact to Low-impact' THEN 1
    WHEN IMPACT_LEVEL = 'Low-impact' THEN 2
    WHEN IMPACT_LEVEL = 'Low to Medium-impact' THEN 3
    WHEN IMPACT_LEVEL = 'Medium-impact' THEN 4
    WHEN IMPACT_LEVEL = 'Medium to High-impact' THEN 5
    WHEN IMPACT_LEVEL = 'High-impact' THEN 6
    WHEN IMPACT_LEVEL LIKE 'Low-impact%' THEN 2
    WHEN IMPACT_LEVEL LIKE 'Medium-impact%' THEN 4
    WHEN IMPACT_LEVEL LIKE 'Medium to High-impact%' THEN 5
    WHEN IMPACT_LEVEL LIKE 'High-impact%' THEN 6
    ELSE -1
  END,
  CASE 
    WHEN CALORIC_BURN = 'Low' THEN 2
    WHEN CALORIC_BURN = 'Low to Medium' THEN 3
    WHEN CALORIC_BURN = 'Medium' THEN 4
    WHEN CALORIC_BURN = 'Medium to High' THEN 5
    WHEN CALORIC_BURN = 'High' THEN 6
    WHEN CALORIC_BURN = 'Very High' THEN 8
    WHEN CALORIC_BURN LIKE 'Low%' THEN 2
    WHEN CALORIC_BURN LIKE 'Medium%' THEN 4
    WHEN CALORIC_BURN LIKE 'High%' THEN 6
    WHEN CALORIC_BURN LIKE 'Very High%' THEN 8
    ELSE -1
  END,
  CONCAT_WS(
    E'\n',
    CONCAT('#Name: ',ACTIVITY_NAME),
    CONCAT('##Category: ',C.CATEGORY),
    CONCAT('##Subcategory: ',S.SUBCATEGORY),
    CONCAT('##Description: ',DESCRIPTION),
    CONCAT('##Primary benefit: ',PRIMARY_BENEFIT),
    CONCAT('##Contraindications: ',CONTRAINDICATIONS),
    CONCAT('##Interesting fact: ',INTERESTING_FACT),
    CONCAT('##Social dynamic: ',SOCIAL_DYNAMIC)
  )
FROM GYM.RAW_ACTIVITIES A
LEFT JOIN GYM.CATEGORIES C
  ON A.CATEGORY=C.CATEGORY
LEFT JOIN GYM.SUBCATEGORIES S
  ON C.ID = S.CATEGORY
    AND A.SUBCATEGORY=S.SUBCATEGORY;
  
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
ALTER TABLE LLM.USAGES ADD COLUMN TRACK UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE LLM.USAGES ADD CONSTRAINT ACTIVITIES_TRACK UNIQUE (TRACK);

CREATE VIEW GYM.VW_SESSIONS AS 
SELECT A.ACTIVITY_NAME, S.DOW,S.TIME,S.DURATION
FROM GYM.ACTIVITIES A
LEFT JOIN GYM.SESSIONS S
ON A.ACTIVITY_CODE=S.ACTIVITY_CODE;